import type { AcademyLesson } from './academy-types';

export const AcademyLessons: AcademyLesson[] = [
  // ═══════════════ NÍVEL 1: EXPLORADOR ═══════════════
  {
    id: 1,
    level: 1,
    title: 'Bem-vindo ao FinDomus',
    subtitle: 'Sua jornada rumo à liberdade financeira começa aqui',
    icon: '🌳',
    mission: null,
    missionEvent: null,
    achievementId: 'first_step',
    steps: [
      {
        id: 'l1-welcome',
        title: 'Bem-vindo ao FinDomus',
        description: 'O FinDomus não é um app de gastos. É um Copiloto completo que vai te ensinar a organizar, planejar e conquistar sua independência financeira. Em 12 aulas práticas, você vai dominar cada ferramenta.',
        placement: 'center',
        order: 1,
      },
      {
        id: 'l1-freedom',
        title: 'O que é Liberdade Financeira?',
        description: 'É quando sua renda passiva (investimentos, aluguéis, dividendos) cobre todas as suas despesas. Você não precisa mais trabalhar para viver — seu dinheiro trabalha por você. O FinDomus calcula exatamente quanto falta para você chegar lá.',
        placement: 'center',
        order: 2,
      },
      {
        id: 'l1-how',
        title: 'Como funciona',
        description: '1. Você cadastra suas contas bancárias. 2. Importa seus extratos (OFX, PDF). 3. A IA categoriza tudo automaticamente. 4. O sistema calcula seu patrimônio, projeta seu futuro e te dá um plano de ação. Simples assim. Sem planilhas.',
        placement: 'center',
        order: 3,
      },
      {
        id: 'l1-dashboard',
        title: 'Seu Painel de Comando',
        description: 'Este é seu Dashboard da Liberdade. Aqui você acompanha: Patrimônio Líquido (tudo que você tem - tudo que deve), Freedom Index (seu progresso rumo à liberdade), e recomendações personalizadas da IA. Por enquanto está vazio — nas próximas aulas vamos preenchê-lo juntos.',
        target: '#tour-step-dashboard',
        placement: 'bottom',
        order: 4,
      },
    ],
  },
  {
    id: 2,
    level: 1,
    title: 'Organize suas Contas',
    subtitle: 'A base de tudo: cadastre suas contas bancárias',
    icon: '🏦',
    mission: 'Cadastrar sua primeira conta bancária',
    missionEvent: 'account:updated',
    achievementId: 'first_account',
    steps: [
      {
        id: 'l2-why',
        title: 'Por que cadastrar contas?',
        description: 'Pense nas contas como os motores do seu dinheiro. Cada real que entra ou sai passa por uma conta. Sem contas cadastradas, o FinDomus não sabe onde seu patrimônio está. Cadastre TODAS: corrente, poupança, carteira, investimentos, cartão.',
        target: '#tour-step-contas-saldo',
        placement: 'bottom',
        order: 1,
      },
      {
        id: 'l2-types',
        title: 'Cada tipo tem uma função',
        description: 'Conta Corrente: seu dia a dia. Poupança: reserva com liquidez. Carteira: dinheiro físico. Investimento: ações, FIIs, renda fixa. Cartão de Crédito: para controle de faturas. Escolha o tipo certo para cada conta.',
        placement: 'center',
        order: 2,
      },
      {
        id: 'l2-action',
        title: 'Hora da prática',
        description: 'Clique em "Adicionar Conta", dê um nome (ex: "Nubank PF"), escolha o tipo e salve. Leva 30 segundos. Esta é sua primeira missão!',
        target: '#tour-step-contas-adicionar',
        placement: 'bottom',
        route: '/contas',
        order: 3,
      },
      {
        id: 'l2-reserve',
        title: 'Sua Reserva de Emergência',
        description: 'Com base no saldo das suas contas, o FinDomus calcula quantos meses de gastos você cobre. A meta recomendada é 6 meses. Imagine que amanhã você perca sua renda — por quanto tempo conseguiria viver? É isso que a reserva mede.',
        target: '#tour-step-contas-reserva',
        placement: 'bottom',
        order: 4,
      },
    ],
  },
  {
    id: 3,
    level: 1,
    title: 'Importe seus Dados',
    subtitle: 'Alimente o sistema com seus extratos bancários',
    icon: '📥',
    mission: 'Importar seu primeiro extrato',
    missionEvent: 'transaction:created',
    achievementId: 'first_import',
    steps: [
      {
        id: 'l3-why',
        title: 'O extrato é a chave',
        description: 'Em vez de digitar cada transação, você importa o extrato do banco em segundos. O FinDomus lê data, valor e descrição. A IA classifica tudo automaticamente. Formatos aceitos: OFX (ideal), PDF de fatura, CSV.',
        target: '#tour-step-import-upload',
        placement: 'bottom',
        route: '/importacoes',
        order: 1,
      },
      {
        id: 'l3-flow',
        title: 'Da importação ao Dashboard',
        description: '1. Baixe o OFX no site do seu banco. 2. Arraste o arquivo para cá. 3. Revise as transações na tabela. 4. Confirme. Pronto — seu Dashboard já mostra dados reais. A IA aprende com cada correção que você fizer.',
        placement: 'center',
        order: 2,
      },
      {
        id: 'l3-review',
        title: 'Revise antes de confirmar',
        description: 'Após o upload, revise as categorias que a IA sugeriu. Se algo estiver errado, corrija — a IA aprende com você. Transações duplicadas (mesmo valor, mesma data) não serão importadas automaticamente.',
        placement: 'center',
        order: 3,
      },
      {
        id: 'l3-ai',
        title: 'A IA aprende com você',
        description: 'Cada vez que você corrige uma categoria, o sistema memoriza. Na próxima importação, a classificação fica ainda mais precisa. É como ter um assistente que fica melhor a cada dia.',
        target: '#tour-step-import-rules',
        placement: 'top',
        order: 4,
      },
      {
        id: 'l3-mission',
        title: 'Sua missão',
        description: 'Arraste um arquivo OFX ou PDF para a área de upload. Se não tiver um agora, pode pular — a missão fica salva para depois.',
        target: '#tour-step-import-ofx',
        placement: 'top',
        order: 5,
      },
    ],
  },
  // ═══════════════ NÍVEL 2: ORGANIZADOR ═══════════════
  {
    id: 4,
    level: 2,
    title: 'Suas Finanças Pessoais',
    subtitle: 'Gerencie cada transação da sua vida',
    icon: '💰',
    mission: 'Criar seu primeiro lançamento manual',
    missionEvent: 'transaction:created',
    achievementId: 'first_transaction',
    steps: [
      {
        id: 'l4-overview',
        title: 'Suas finanças, mês a mês',
        description: 'Aqui você gerencia cada transação da sua vida pessoal. Tudo que você importou aparece aqui, organizado por mês. Você pode criar, editar, excluir e categorizar cada lançamento.',
        target: '#tour-step-pessoal-stats',
        placement: 'bottom',
        route: '/pessoal',
        order: 1,
      },
      {
        id: 'l4-score',
        title: 'O placar do seu mês',
        description: 'Receitas (o que entrou) menos Despesas (o que saiu) = seu resultado. Verde: você gastou menos do que ganhou. Vermelho: atenção, está no negativo. Esse número é seu fluxo de caixa real.',
        placement: 'center',
        order: 2,
      },
      {
        id: 'l4-chart',
        title: 'Para onde seu dinheiro vai?',
        description: 'O gráfico mostra cada categoria de gasto. Clique em uma fatia para filtrar a tabela. Se "Alimentação" está muito grande, talvez seja hora de cozinhar mais em casa.',
        target: '#tour-step-pessoal-grafico',
        placement: 'top',
        order: 3,
      },
      {
        id: 'l4-manual',
        title: 'Nem tudo vem do extrato',
        description: 'Use "Novo Lançamento" para despesas em dinheiro, transferências ou receitas que não aparecem no extrato. Crie seu primeiro lançamento agora — esta é sua missão.',
        target: '#tour-step-pessoal-novo',
        placement: 'bottom',
        order: 4,
      },
      {
        id: 'l4-closure',
        title: 'Fechar o mês',
        description: 'No fim do mês, clique em "Fechar mês". Isso congela os dados daquele período e calcula seu resultado oficial — como na contabilidade real. Depois de fechado, os lançamentos não podem mais ser alterados.',
        target: '#tour-step-pessoal-fechar',
        placement: 'bottom',
        order: 5,
      },
    ],
  },
  {
    id: 5,
    level: 2,
    title: 'Empresas',
    subtitle: 'Separe suas finanças PJ das pessoais',
    icon: '🏢',
    mission: 'Cadastrar sua primeira empresa',
    missionEvent: 'data:changed',
    achievementId: 'first_company',
    steps: [
      {
        id: 'l5-pf-pj',
        title: 'PF e PJ são vidas diferentes',
        description: 'Misturar as contas da empresa com as pessoais é o erro número 1 de quem empreende. O FinDomus mantém tudo separado: cada empresa tem seu próprio DRE, contas e obrigações fiscais. Se você não tem empresa, pode pular esta aula.',
        target: '#tour-step-empresas-selector',
        placement: 'bottom',
        route: '/empresas',
        order: 1,
      },
      {
        id: 'l5-create',
        title: 'Cadastre sua empresa',
        description: 'Clique em "Nova Empresa", digite o nome e salve. Depois, vincule as contas PJ à empresa. Cada conta PJ precisa estar associada a uma empresa para os relatórios funcionarem corretamente.',
        placement: 'center',
        order: 2,
      },
      {
        id: 'l5-dre',
        title: 'DRE Empresarial',
        description: 'O DRE (Demonstrativo de Resultado) mostra a saúde financeira da sua empresa: receita bruta, impostos, despesas e lucro líquido. É como o "placar" do seu negócio. Os dados vêm das transações PJ importadas.',
        placement: 'center',
        order: 3,
      },
    ],
  },
  {
    id: 6,
    level: 2,
    title: 'Passivos',
    subtitle: 'Controle suas dívidas com inteligência',
    icon: '📊',
    mission: 'Cadastrar seu primeiro passivo',
    missionEvent: 'liability:created',
    achievementId: 'first_liability',
    steps: [
      {
        id: 'l6-debt',
        title: 'Dívidas bem gerenciadas',
        description: 'Uma dívida não é vilã — o problema é não saber o impacto real dela. Financiamento, empréstimo, cartão parcelado: cada um tem juros, prazo e impacto diferente no seu patrimônio.',
        target: '#tour-step-passivos-resumo',
        placement: 'bottom',
        route: '/passivos',
        order: 1,
      },
      {
        id: 'l6-create',
        title: 'Cadastre um passivo',
        description: 'Nome, tipo, valor da parcela, total de parcelas e saldo devedor. O sistema calcula automaticamente quanto falta pagar e projeta a data de quitação.',
        placement: 'center',
        order: 2,
      },
      {
        id: 'l6-simulate',
        title: 'Simule a quitação',
        description: 'Clique em "Simular Amortização" para ver quanto você economiza se antecipar parcelas. A simulação mostra o impacto no seu patrimônio e no prazo de quitação. Esse valor pode ser reinvestido.',
        target: '#tour-step-passivos-simular',
        placement: 'bottom',
        order: 3,
      },
    ],
  },
  // ═══════════════ NÍVEL 3: PLANEJADOR ═══════════════
  {
    id: 7,
    level: 3,
    title: 'Planejamento Financeiro',
    subtitle: 'O coração do FinDomus — defina seu futuro',
    icon: '🎯',
    mission: 'Salvar seu primeiro orçamento',
    missionEvent: 'planning:updated',
    achievementId: 'first_budget',
    steps: [
      {
        id: 'l7-intro',
        title: 'O coração do FinDomus',
        description: 'O Planejamento é onde você define para onde seu dinheiro vai. Não é sobre cortar gastos — é sobre decidir conscientemente o que é prioridade. Esta é a aula mais longa porque é a mais importante.',
        target: '#tour-step-plan-profile',
        placement: 'bottom',
        route: '/planejamento',
        order: 1,
      },
      {
        id: 'l7-503020',
        title: 'O método 50/30/20',
        description: '50% para gastos essenciais (moradia, alimentação, transporte). 30% para estilo de vida (lazer, compras, viagens). 20% para construir patrimônio (investimentos, reserva). Ajuste os percentuais para sua realidade.',
        placement: 'center',
        order: 2,
      },
      {
        id: 'l7-budget',
        title: 'Orçamento doméstico',
        description: 'Cada categoria tem um limite. A barra colorida mostra o planejado vs o real. Verde: dentro da meta. Amarelo: atenção, quase no limite. Vermelho: estourou o orçamento.',
        target: '#tour-step-plan-orcamento',
        placement: 'top',
        order: 3,
      },
      {
        id: 'l7-freedom',
        title: 'Freedom Index — Seu termômetro',
        description: 'De 0 a 100 pontos. 7 pilares: dívidas, margem, reserva, patrimônio, aportes, renda passiva, diversificação. Cada pilar tem um peso. O índice mostra exatamente o que você precisa melhorar para subir de nível.',
        placement: 'center',
        order: 4,
      },
      {
        id: 'l7-forecast',
        title: 'Previsão dos próximos meses',
        description: 'Com base nos seus dados reais, o sistema projeta seu fluxo de caixa nos próximos 6 meses. Isso te ajuda a planejar gastos grandes e evitar surpresas.',
        placement: 'center',
        order: 5,
      },
      {
        id: 'l7-actions',
        title: 'Seu plano de ação',
        description: 'Recomendações priorizadas: o que fazer primeiro, o que gera mais impacto, quanto cada ação aumenta seu Freedom Index. Siga a ordem sugerida para evoluir mais rápido.',
        target: '#tour-step-dashboard-actions',
        placement: 'left',
        order: 6,
      },
      {
        id: 'l7-mission',
        title: 'Sua missão',
        description: 'Ajuste os sliders de distribuição até atingir 100%. Depois clique em Salvar. Este é seu primeiro planejamento — ele vai guiar todas as suas decisões financeiras a partir de agora.',
        target: '#tour-step-plan-metas',
        placement: 'bottom',
        order: 7,
      },
    ],
  },
  // ═══════════════ NÍVEL 4: INVESTIDOR ═══════════════
  {
    id: 8,
    level: 4,
    title: 'Investimentos',
    subtitle: 'Faça seu dinheiro trabalhar por você',
    icon: '📈',
    mission: 'Cadastrar seu primeiro investimento',
    missionEvent: 'investment:created',
    achievementId: 'first_investment',
    steps: [
      {
        id: 'l8-why',
        title: 'Investir não é só para ricos',
        description: 'Com R$ 100 por mês bem investidos a 10% ao ano, em 30 anos você terá mais de R$ 200 mil. O segredo é consistência e tempo. Os juros compostos fazem o trabalho pesado.',
        target: '#tour-step-invest-wallet',
        placement: 'bottom',
        route: '/investimentos',
        order: 1,
      },
      {
        id: 'l8-types',
        title: 'Tipos de investimento',
        description: 'Ações: participação em empresas. FIIs: fundos imobiliários que pagam aluguel mensal. Tesouro Direto: títulos do governo. CDB/LCI/LCA: renda fixa de bancos. Cada um tem risco e retorno diferentes — diversificar é a chave.',
        placement: 'center',
        order: 2,
      },
      {
        id: 'l8-create',
        title: 'Cadastre seu primeiro investimento',
        description: 'Clique em "Novo Investimento", preencha tipo, valor e corretora. Se tiver B3 ou notas de corretora (XP, BTG), importe na Central de Importação — os ativos aparecem automaticamente.',
        target: '#tour-step-invest-aportes',
        placement: 'top',
        order: 3,
      },
      {
        id: 'l8-read',
        title: 'Como ler sua carteira',
        description: 'Rentabilidade: quanto seu dinheiro cresceu. Dividend Yield: quanto você recebe de proventos por ano. Health Score: nota de 0 a 100 da saúde da sua carteira (diversificação, concentração, liquidez).',
        placement: 'center',
        order: 4,
      },
      {
        id: 'l8-passive',
        title: 'Renda Passiva — o caminho para a liberdade',
        description: 'Dividendos de ações, aluguéis de FIIs, juros de renda fixa. Essa é sua renda passiva real. Ela entra no cálculo do Freedom Index. Quanto maior sua renda passiva, mais perto da liberdade financeira.',
        target: '#tour-step-invest-proventos',
        placement: 'top',
        order: 5,
      },
    ],
  },
  // ═══════════════ NÍVEL 5: MESTRE ═══════════════
  {
    id: 9,
    level: 5,
    title: 'Relatórios',
    subtitle: 'Interpretação avançada das suas finanças',
    icon: '📄',
    mission: null,
    missionEvent: null,
    achievementId: null,
    steps: [
      {
        id: 'l9-dre',
        title: 'DRE — Sua demonstração de resultado',
        description: 'O DRE Pessoal mostra: receita total, despesas por categoria, e sua taxa de acumulação (quanto sobra para investir). É o "imposto de renda" das suas finanças. Use para comparar meses e ver sua evolução.',
        target: '#tour-step-report-dre',
        placement: 'bottom',
        route: '/relatorios',
        order: 1,
      },
      {
        id: 'l9-export',
        title: 'Exporte seus dados',
        description: 'Gere relatórios em PDF para seu contador ou planejador financeiro. Exporte em OFX para levar seus dados para outros sistemas. Tudo com um clique.',
        target: '#tour-step-report-exportar',
        placement: 'left',
        order: 2,
      },
    ],
  },
  {
    id: 10,
    level: 5,
    title: 'Assinaturas e Custos Fixos',
    subtitle: 'Controle o que é recorrente',
    icon: '🔄',
    mission: null,
    missionEvent: null,
    achievementId: null,
    steps: [
      {
        id: 'l10-impact',
        title: 'O impacto silencioso',
        description: 'Netflix R$ 39,90 + Spotify R$ 21,90 + Academia R$ 119,90 = R$ 181,70 por mês. Em 10 anos: R$ 21.804. Some todas as suas assinaturas e veja o impacto real no seu orçamento.',
        target: '#tour-step-assinaturas-total',
        placement: 'bottom',
        route: '/assinaturas',
        order: 1,
      },
      {
        id: 'l10-ai',
        title: 'A IA detecta por você',
        description: 'O sistema analisa seu histórico e sugere automaticamente despesas recorrentes que você ainda não cadastrou. Revise as sugestões e importe com um clique.',
        target: '#tour-step-assinaturas-calendario',
        placement: 'top',
        order: 2,
      },
    ],
  },
  {
    id: 11,
    level: 5,
    title: 'IA — Seu Copiloto Financeiro',
    subtitle: 'Um consultor que conhece todos os seus dados',
    icon: '🤖',
    mission: 'Fazer sua primeira pergunta ao Copiloto',
    missionEvent: 'ai:chat',
    achievementId: 'first_ai_chat',
    steps: [
      {
        id: 'l11-intro',
        title: 'Seu consultor 24 horas',
        description: 'A IA do FinDomus conhece seus dados reais: saldos, gastos, investimentos, dívidas. Pergunte em português natural como se fosse seu consultor financeiro pessoal.',
        target: '#tour-step-chat-botao',
        placement: 'left',
        order: 1,
      },
      {
        id: 'l11-examples',
        title: 'O que você pode perguntar',
        description: '"Qual foi meu maior gasto este mês?" "Minha reserva está adequada?" "Quanto meus investimentos renderam?" "Vale a pena quitar meu financiamento?" "Quanto falta para eu me aposentar?"',
        target: '#tour-step-chat-exemplo',
        placement: 'top',
        order: 2,
      },
      {
        id: 'l11-mission',
        title: 'Sua missão',
        description: 'Clique no botão flutuante no canto inferior direito e faça sua primeira pergunta. Experimente: "Como está minha saúde financeira hoje?"',
        target: '#tour-step-chat-input',
        placement: 'top',
        order: 3,
      },
    ],
  },
  {
    id: 12,
    level: 5,
    title: 'Dashboard — Sua Central de Comando',
    subtitle: 'Agora você entende cada número',
    icon: '🏠',
    mission: null,
    missionEvent: null,
    achievementId: null,
    steps: [
      {
        id: 'l12-networth',
        title: 'Patrimônio Líquido',
        description: 'O número mais importante: tudo que você tem (contas + investimentos) menos tudo que você deve (dívidas). Esse é o valor real da sua riqueza. Acompanhe a evolução no gráfico mensal.',
        target: '#tour-step-dashboard-summary',
        placement: 'bottom',
        route: '/',
        order: 1,
      },
      {
        id: 'l12-flow',
        title: 'Fluxo de Caixa',
        description: 'Entradas menos saídas. O gráfico mostra mês a mês se você está gastando mais do que ganha. A tendência é mais importante que o valor de um mês isolado.',
        target: '#tour-step-dashboard-chart',
        placement: 'top',
        order: 2,
      },
      {
        id: 'l12-freedom',
        title: 'Freedom Index e Timeline',
        description: 'Seu score de liberdade + projeção de quando você atinge cada nível. Cada ação que você realiza (quitar dívida, aumentar aporte) move essa agulha. Acompanhe semanalmente.',
        placement: 'center',
        order: 3,
      },
      {
        id: 'l12-ai',
        title: 'Recomendações da IA',
        description: 'Ações priorizadas para subir seu score. Siga a ordem sugerida. Cada ação concluída te aproxima da independência financeira.',
        target: '#tour-step-dashboard-actions',
        placement: 'left',
        order: 4,
      },
      {
        id: 'l12-finish',
        title: '🎉 Você é um Mestre da Liberdade Financeira!',
        description: 'Você concluiu a Academia FinDomus. Agora você sabe: organizar contas, importar extratos, gerenciar transações, planejar orçamento, investir com estratégia, interpretar relatórios e usar a IA como consultora. Sua jornada continua — o Dashboard é seu piloto automático.',
        placement: 'center',
        order: 5,
      },
    ],
  },
];

export function getLessonById(id: number): AcademyLesson | undefined {
  return AcademyLessons.find((l) => l.id === id);
}

export function getLessonsByLevel(level: number): AcademyLesson[] {
  return AcademyLessons.filter((l) => l.level === level);
}
